import {
  LayoutDashboard, Users, Package, Beef, Factory, Building2, CalendarRange,
  UserCog, BarChart3, FileSearch, MessageSquare, LogIn, ShieldCheck,
  ClipboardList, Calendar, Truck, GraduationCap, Mail, Phone, MapPin,
  Globe, Share2, ChevronDown, Menu, X, Search, CheckCircle, Clock,
  AlertTriangle, Check, Info, ArrowUpRight, Settings, Plus, Edit,
  Trash2, Eye, MoreVertical, LogOut, User, ArrowLeft, ArrowRight,
  Upload, Download, Filter, RefreshCw, ExternalLink, Bell
} from 'lucide-react';

export {
  LayoutDashboard, Users, Package, Beef, Factory, Building2, CalendarRange,
  UserCog, BarChart3, FileSearch, MessageSquare, LogIn, ShieldCheck,
  ClipboardList, Calendar, Truck, GraduationCap, Mail, Phone, MapPin,
  Globe, Share2, ChevronDown, Menu, X, Search, CheckCircle, Clock,
  AlertTriangle, Check, Info, ArrowUpRight, Settings, Plus, Edit,
  Trash2, Eye, MoreVertical, LogOut, User, ArrowLeft, ArrowRight,
  Upload, Download, Filter, RefreshCw, ExternalLink, Bell
};

export const Icons = {
  dashboard: LayoutDashboard,
  beneficiaries: Users,
  distribution: Package,
  inventory: Beef,
  suppliers: Factory,
  centers: Building2,
  sessions: CalendarRange,
  users: UserCog,
  reports: BarChart3,
  audit: FileSearch,
  sms: MessageSquare,
  login: LogIn,
  shield: ShieldCheck,
  register: ClipboardList,
  calendar: Calendar,
  truck: Truck,
  graduation: GraduationCap,
  mail: Mail,
  phone: Phone,
  location: MapPin,
  globe: Globe,
  share: Share2,
  chevronDown: ChevronDown,
  menu: Menu,
  x: X,
  search: Search,
  checkCircle: CheckCircle,
  clock: Clock,
  alertTriangle: AlertTriangle,
  check: Check,
  info: Info,
  externalLink: ArrowUpRight,
  settings: Settings,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  eye: Eye,
  moreVertical: MoreVertical,
  logOut: LogOut,
  user: User,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  upload: Upload,
  download: Download,
  filter: Filter,
  refresh: RefreshCw,
  bell: Bell,
  building: Building2,
  family: Users,
  messageSquare: MessageSquare,
  package: Package,
  beef: Beef,
} as const;
